### ISSUE TITLE
ユーザー登録情報 「言語」「フレームワーク」「その他スキル」

### ISSUE THREAD

**Issue by Kazuya-Sakamoto** [team-up-develop/teamup-api#3]
## 概要
ユーザーの情報を取得する際に以下のスキル情報を取得できるようにする。
案件と同様、「言語」「フレームワーク」「その他スキル」3つの項目で取得できるようにする。

### API
> http://localhost:8888/api/v1/user/id

## 画像
<img width="1432" alt="スクリーンショット 2020-11-29 21 48 25" src="https://user-images.githubusercontent.com/56709557/100542336-9e71cb00-328c-11eb-827a-c84daaed8194.png">

## 確認項目
- [ ] 複数言語が登録できるよにする
- [ ] 編集 / 登録 / 削除 ができるようにする

**Comment by tsubaoza0901** [comment]
done
