### ISSUE TITLE
チャットでメッセージを取得する際に降順(新しいものが配列上部に)をやめる

### ISSUE THREAD

**Issue by Kazuya-Sakamoto** [team-up-develop/teamup-api#30]
## 概要
チャット内容が新しいもの順になってしまっている。

### API
> http://localhost:8090/api/v1/chat_messages?job_id=11

## 画像
<img width="1440" alt="スクリーンショット 2021-01-31 17 51 59" src="https://user-images.githubusercontent.com/56709557/106379118-1b383700-63ed-11eb-9c43-24be10978d27.png">

## 確認項目
- [ ] 古いものから並ぶようにできていること

**Comment by tsubaoza0901** [comment]
done

**Comment by Kazuya-Sakamoto** [comment]
確認済みです！
