### ISSUE TITLE
/chat_messages?job_id=1 のresponseの値を変更してほしい

### ISSUE THREAD

**Issue by Kazuya-Sakamoto** [team-up-develop/teamup-api#37]
## 概要
現状
```user_name```がかえって来ているが、アプリ内で使用したいのは```login_name```
のため、```login_name```を返すように変更お願いします。

ちなみにuser_nameは使用しません。

## API
```/chat_messages?job_id=1 ```
## 参考画像
<img width="451" alt="スクリーンショット 2021-02-05 14 16 43" src="https://user-images.githubusercontent.com/56709557/106992869-cc0f4f00-67bc-11eb-9789-1b55a5cfe893.png">

**Comment by tsubaoza0901** [comment]
done
