### ISSUE TITLE
案件 降順にしてほしい

### ISSUE THREAD

**Issue by Kazuya-Sakamoto** [team-up-develop/teamup-api#5]
## 概要
案件を取得する時に 降順(新しいものが[0])になるように取得したい。
毎回毎回降順にするという処理を書かなければイケナイため、
コードが肥大化する。

### API
**GET**
> http://localhost:8888/api/v1/job

## 画像
特になし

## 確認項目
- [ ] 案件を取得した時に新しい順になっていること

**Comment by tsubaoza0901** [comment]
done
